# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'Delete all draft releases'
description: 'Delete all draft releases'
author: "jakeswenson"
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "red"
  icon: "delete"


  
